"""
Bahis / Betting module for Premier Ligi.

- User points wallet (default 100)
- Match odds (auto-generated by Groq LLaMA 3.3 70B, override-able by founder)
- Bet types: MS (Match Result), GOAL_O_U (2.5), CORNER_O_U (4.5)
- Coupons (single or combo). One selection per match per coupon.
- Auto-settlement when admin finalizes match (score + corners).
- Founder controls: cancel coupon + refund, override result, lock bet types.
"""
import os
import json
import uuid
import logging
import asyncio
from datetime import datetime, timezone, timedelta
from typing import List, Optional, Dict, Any

import httpx
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, Field

from db import db
from auth import get_current_user, require_founder
from media import broadcast_push

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/betting", tags=["betting"])

MIN_STAKE = 30
DEFAULT_STARTING_POINTS = 100
GOAL_REWARD = 15  # Coin per goal awarded to the team owner (manager user)

BET_TYPES = {"MS", "GOAL_O_U", "CORNER_O_U"}
SELECTIONS = {
    "MS": {"1", "X", "2"},
    "GOAL_O_U": {"OVER_2_5", "UNDER_2_5"},
    "CORNER_O_U": {"OVER_4_5", "UNDER_4_5"},
}
ODDS_KEYS = {
    "MS": {"1": "ms_1", "X": "ms_x", "2": "ms_2"},
    "GOAL_O_U": {"OVER_2_5": "goal_over_2_5", "UNDER_2_5": "goal_under_2_5"},
    "CORNER_O_U": {"OVER_4_5": "corner_over_4_5", "UNDER_4_5": "corner_under_4_5"},
}
ALL_ODDS_KEYS = [
    "ms_1", "ms_x", "ms_2",
    "goal_over_2_5", "goal_under_2_5",
    "corner_over_4_5", "corner_under_4_5",
]

DEFAULT_ODDS = {
    "ms_1": 2.20,
    "ms_x": 3.10,
    "ms_2": 2.70,
    "goal_over_2_5": 1.75,
    "goal_under_2_5": 1.95,
    "corner_over_4_5": 1.85,
    "corner_under_4_5": 1.85,
}


def now_iso():
    return datetime.now(timezone.utc).isoformat()


def new_id():
    return str(uuid.uuid4())


# ----------------------------- Models -----------------------------
class CouponItem(BaseModel):
    match_id: str
    bet_type: str  # 'MS' | 'GOAL_O_U' | 'CORNER_O_U'
    selection: str  # '1','X','2','OVER_2_5','UNDER_2_5','OVER_4_5','UNDER_4_5'


class CouponCreateReq(BaseModel):
    items: List[CouponItem]
    stake: int


class OddsOverrideReq(BaseModel):
    match_id: str
    odds: Dict[str, float]


class BetLockReq(BaseModel):
    match_id: str
    bet_type: str
    locked: bool


class UserPointsReq(BaseModel):
    delta: Optional[int] = None
    set_to: Optional[int] = None
    reason: str = ""


class CouponStatusReq(BaseModel):
    status: str  # 'WON' | 'LOST' | 'PENDING'


# ----------------------------- Helpers -----------------------------
async def ensure_user_points(user_id: str) -> int:
    u = await db.users.find_one({"id": user_id}, {"points": 1})
    if u is None:
        return 0
    if "points" not in u:
        await db.users.update_one({"id": user_id}, {"$set": {"points": DEFAULT_STARTING_POINTS}})
        return DEFAULT_STARTING_POINTS
    return int(u.get("points") or 0)


async def get_match_odds(match_id: str) -> Dict[str, float]:
    m = await db.matches.find_one({"id": match_id}, {"odds": 1, "bet_locks": 1})
    if not m:
        return dict(DEFAULT_ODDS)
    odds = m.get("odds") or {}
    result = dict(DEFAULT_ODDS)
    result.update({k: float(v) for k, v in odds.items() if k in ALL_ODDS_KEYS and isinstance(v, (int, float))})
    return result


def bet_type_of_selection(selection: str) -> Optional[str]:
    for bt, sels in SELECTIONS.items():
        if selection in sels:
            return bt
    return None


# ----------------------------- Groq Odds Generator -----------------------------
GROQ_URL = "https://api.groq.com/openai/v1/chat/completions"

SYSTEM_PROMPT_ODDS = (
    "You are a professional football (soccer) betting odds compiler for an eFootball amateur league. "
    "Given two teams' recent form and head-to-head data, produce realistic decimal odds. "
    "Rules:\n"
    "1) Return STRICT JSON only, no prose, no markdown fences.\n"
    "2) Fields (all required, decimal >= 1.10):\n"
    "   ms_1, ms_x, ms_2, goal_over_2_5, goal_under_2_5, corner_over_4_5, corner_under_4_5\n"
    "3) MS probabilities (1/odd) must sum roughly to 1.05-1.15 (bookmaker margin).\n"
    "4) Over/Under pairs must also sum roughly to 1.05-1.15 (margin).\n"
    "5) Cold-start rule: if a team has fewer than 5 matches OR no corner history, use balanced ~1.85/~1.85 for corners.\n"
    "6) Realistic ranges: MS between 1.30 and 8.00. O/U between 1.40 and 3.20.\n"
    "7) Round to two decimals."
)


async def generate_odds_via_groq(context: Dict[str, Any]) -> Dict[str, float]:
    api_key = os.getenv("GROQ_API_KEY", "").strip()
    model = os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile").strip()
    if not api_key:
        logger.warning("GROQ_API_KEY missing; returning default odds")
        return dict(DEFAULT_ODDS)

    prompt = (
        "Return JSON odds for the upcoming match.\n"
        f"HOME_TEAM: {context.get('home_name')}\n"
        f"AWAY_TEAM: {context.get('away_name')}\n"
        f"HOME_LAST5: {json.dumps(context.get('home_last5', []))}\n"
        f"AWAY_LAST5: {json.dumps(context.get('away_last5', []))}\n"
        f"HEAD_TO_HEAD: {json.dumps(context.get('h2h', {}))}\n"
        f"HOME_MATCHES_PLAYED: {context.get('home_played', 0)}\n"
        f"AWAY_MATCHES_PLAYED: {context.get('away_played', 0)}\n"
        f"HOME_AVG_CORNERS: {context.get('home_avg_corners')}\n"
        f"AWAY_AVG_CORNERS: {context.get('away_avg_corners')}\n"
        f"LEAGUE_AVG_GOALS_PER_MATCH: {context.get('league_avg_goals', 2.7)}\n"
        f"LEAGUE_AVG_CORNERS_PER_MATCH: {context.get('league_avg_corners', 5.5)}\n"
    )

    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT_ODDS},
            {"role": "user", "content": prompt},
        ],
        "response_format": {"type": "json_object"},
        "temperature": 0.4,
        "max_tokens": 300,
    }
    headers = {"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
    try:
        async with httpx.AsyncClient(timeout=25.0) as client:
            r = await client.post(GROQ_URL, json=payload, headers=headers)
            r.raise_for_status()
            data = r.json()
            content = data["choices"][0]["message"]["content"]
            parsed = json.loads(content)
    except Exception as exc:
        logger.warning("Groq odds generation failed: %s", exc)
        return dict(DEFAULT_ODDS)

    out = dict(DEFAULT_ODDS)
    for k in ALL_ODDS_KEYS:
        v = parsed.get(k)
        try:
            fv = float(v)
            if 1.10 <= fv <= 20.0:
                out[k] = round(fv, 2)
        except (TypeError, ValueError):
            pass
    return out


async def _team_recent_matches(team_id: str, limit: int = 5) -> List[Dict[str, Any]]:
    cursor = db.matches.find(
        {"status": "finished",
         "$or": [{"home_team_id": team_id}, {"away_team_id": team_id}],
         "home_score": {"$ne": None}},
        {"_id": 0}
    ).sort([("finished_at", -1)]).limit(limit)
    out = []
    async for m in cursor:
        is_home = m["home_team_id"] == team_id
        gf = m.get("home_score", 0) if is_home else m.get("away_score", 0)
        ga = m.get("away_score", 0) if is_home else m.get("home_score", 0)
        cf = m.get("home_corners") if is_home else m.get("away_corners")
        ca = m.get("away_corners") if is_home else m.get("home_corners")
        out.append({
            "gf": gf, "ga": ga,
            "result": "W" if gf > ga else ("D" if gf == ga else "L"),
            "corners_for": cf, "corners_against": ca,
        })
    return out


async def _team_stats(team_id: str) -> Dict[str, Any]:
    matches = await db.matches.find(
        {"status": "finished",
         "$or": [{"home_team_id": team_id}, {"away_team_id": team_id}],
         "home_score": {"$ne": None}},
        {"_id": 0}
    ).to_list(2000)
    played = len(matches)
    corners = []
    for m in matches:
        is_home = m["home_team_id"] == team_id
        c = m.get("home_corners") if is_home else m.get("away_corners")
        if c is not None:
            corners.append(int(c))
    avg_corners = round(sum(corners) / len(corners), 2) if corners else None
    return {"played": played, "avg_corners": avg_corners}


async def _h2h_stats(a: str, b: str) -> Dict[str, Any]:
    matches = await db.matches.find(
        {"status": "finished",
         "$or": [
             {"home_team_id": a, "away_team_id": b},
             {"home_team_id": b, "away_team_id": a},
         ],
         "home_score": {"$ne": None}},
        {"_id": 0}
    ).to_list(500)
    wins_a = wins_b = draws = 0
    goals_a = goals_b = 0
    for m in matches:
        hs = int(m.get("home_score") or 0)
        as_ = int(m.get("away_score") or 0)
        if m["home_team_id"] == a:
            goals_a += hs; goals_b += as_
        else:
            goals_a += as_; goals_b += hs
        # winner
        if hs == as_:
            draws += 1
        else:
            winner = m["home_team_id"] if hs > as_ else m["away_team_id"]
            if winner == a: wins_a += 1
            else: wins_b += 1
    return {
        "total": len(matches),
        "wins_a": wins_a, "wins_b": wins_b, "draws": draws,
        "goals_a": goals_a, "goals_b": goals_b,
    }


async def build_odds_context(match: dict) -> Dict[str, Any]:
    home_team = await db.teams.find_one({"id": match["home_team_id"]}, {"name": 1})
    away_team = await db.teams.find_one({"id": match["away_team_id"]}, {"name": 1})
    home_last5 = await _team_recent_matches(match["home_team_id"], 5)
    away_last5 = await _team_recent_matches(match["away_team_id"], 5)
    home_stats = await _team_stats(match["home_team_id"])
    away_stats = await _team_stats(match["away_team_id"])
    h2h = await _h2h_stats(match["home_team_id"], match["away_team_id"])

    # League averages
    all_finished = await db.matches.find(
        {"status": "finished", "home_score": {"$ne": None}},
        {"_id": 0, "home_score": 1, "away_score": 1, "home_corners": 1, "away_corners": 1}
    ).to_list(5000)
    if all_finished:
        avg_goals = round(sum((m.get("home_score") or 0) + (m.get("away_score") or 0) for m in all_finished) / len(all_finished), 2)
        c_list = [(m.get("home_corners") or 0) + (m.get("away_corners") or 0) for m in all_finished if m.get("home_corners") is not None]
        avg_corners = round(sum(c_list) / len(c_list), 2) if c_list else 5.5
    else:
        avg_goals = 2.7
        avg_corners = 5.5

    return {
        "home_name": home_team.get("name") if home_team else "?",
        "away_name": away_team.get("name") if away_team else "?",
        "home_last5": home_last5,
        "away_last5": away_last5,
        "home_played": home_stats["played"],
        "away_played": away_stats["played"],
        "home_avg_corners": home_stats["avg_corners"],
        "away_avg_corners": away_stats["avg_corners"],
        "h2h": h2h,
        "league_avg_goals": avg_goals,
        "league_avg_corners": avg_corners,
    }


async def generate_and_save_odds(match_id: str) -> Dict[str, float]:
    m = await db.matches.find_one({"id": match_id}, {"_id": 0})
    if not m:
        raise HTTPException(404, "Maç bulunamadı")
    if m.get("status") in ("finished", "canceled"):
        # Not necessary but harmless.
        pass
    ctx = await build_odds_context(m)
    odds = await generate_odds_via_groq(ctx)
    await db.matches.update_one({"id": match_id}, {"$set": {"odds": odds, "odds_generated_at": now_iso()}})
    return odds


# ----------------------------- Coupon Settlement -----------------------------
def _selection_result(bet_type: str, selection: str, home_score: int, away_score: int,
                      home_corners: Optional[int], away_corners: Optional[int]) -> Optional[str]:
    """Return 'WON'|'LOST', or None if data insufficient (e.g. no corners)."""
    if bet_type == "MS":
        outcome = "1" if home_score > away_score else ("2" if away_score > home_score else "X")
        return "WON" if selection == outcome else "LOST"
    if bet_type == "GOAL_O_U":
        total = home_score + away_score
        over = total > 2.5  # >2.5 means >=3
        if selection == "OVER_2_5":
            return "WON" if over else "LOST"
        return "WON" if not over else "LOST"
    if bet_type == "CORNER_O_U":
        if home_corners is None or away_corners is None:
            return None
        total = home_corners + away_corners
        over = total > 4.5
        if selection == "OVER_4_5":
            return "WON" if over else "LOST"
        return "WON" if not over else "LOST"
    return None


async def _match_snapshot(match_id: str) -> Optional[Dict[str, Any]]:
    m = await db.matches.find_one(
        {"id": match_id},
        {"_id": 0, "status": 1, "home_score": 1, "away_score": 1,
         "home_corners": 1, "away_corners": 1, "home_team_id": 1, "away_team_id": 1}
    )
    return m


async def settle_coupons_for_match(match_id: str):
    """Called after admin finalizes a match. Re-evaluates all coupons touching this match."""
    coupons = await db.coupons.find({"items.match_id": match_id, "status": "PENDING"}, {"_id": 0}).to_list(5000)
    for coupon in coupons:
        await _settle_one(coupon)


async def _settle_one(coupon: dict):
    """Evaluate coupon; if all items finalized, mark WON/LOST and pay out."""
    items = coupon.get("items", [])
    new_items = []
    any_lost = False
    all_done = True
    for it in items:
        m = await _match_snapshot(it["match_id"])
        if not m or m.get("status") not in ("finished",):
            new_items.append({**it, "status": "PENDING"})
            all_done = False
            continue
        hs = int(m.get("home_score") or 0)
        as_ = int(m.get("away_score") or 0)
        hc = m.get("home_corners")
        ac = m.get("away_corners")
        res = _selection_result(it["bet_type"], it["selection"], hs, as_, hc, ac)
        if res is None:
            # Corner data missing → still pending
            new_items.append({**it, "status": "PENDING"})
            all_done = False
            continue
        new_items.append({**it, "status": res})
        if res == "LOST":
            any_lost = True

    update = {"items": new_items}
    if any_lost:
        update["status"] = "LOST"
        update["settled_at"] = now_iso()
    elif all_done:
        # All WON
        update["status"] = "WON"
        update["settled_at"] = now_iso()
        payout = round(coupon["stake"] * coupon["total_odd"])
        update["payout"] = payout
        # Credit user
        await db.users.update_one({"id": coupon["user_id"]}, {"$inc": {"points": payout}})
    else:
        update["status"] = "PENDING"

    await db.coupons.update_one({"id": coupon["id"]}, {"$set": update})

    # Push notification on final settle
    if update.get("status") in ("WON", "LOST"):
        try:
            user = await db.users.find_one({"id": coupon["user_id"]}, {"push_subscription": 1, "username": 1})
            title = "🎉 KUPONUN KAZANDI!" if update["status"] == "WON" else "💔 Kupon Kaybetti"
            body = (f"+{update.get('payout', 0)} coin • {len(new_items)} maçlı"
                    if update["status"] == "WON" else "Bir sonraki sefere.")
            await broadcast_push(title, body, "/my-coupons")
        except Exception as exc:
            logger.warning("push settle failed: %s", exc)


# ----------------------------- Match hooks (called from server.py) -----------------------------
async def on_match_finished(match_id: str, home_score: int, away_score: int,
                            home_corners: Optional[int], away_corners: Optional[int]):
    """Called when admin finishes a match. Awards goal coins + settles coupons."""
    m = await db.matches.find_one({"id": match_id}, {"_id": 0})
    if not m:
        return
    # Award +15 per goal to each team's owner (manager user), only once per match.
    if not m.get("goal_rewards_paid"):
        home = await db.teams.find_one({"id": m["home_team_id"]}, {"user_id": 1})
        away = await db.teams.find_one({"id": m["away_team_id"]}, {"user_id": 1})
        if home and home.get("user_id") and home_score > 0:
            await db.users.update_one({"id": home["user_id"]}, {"$inc": {"points": GOAL_REWARD * int(home_score)}})
        if away and away.get("user_id") and away_score > 0:
            await db.users.update_one({"id": away["user_id"]}, {"$inc": {"points": GOAL_REWARD * int(away_score)}})
        await db.matches.update_one({"id": match_id}, {"$set": {"goal_rewards_paid": True}})

    await settle_coupons_for_match(match_id)


# ----------------------------- Endpoints -----------------------------
@router.get("/wallet")
async def read_wallet(user: dict = Depends(get_current_user)):
    pts = await ensure_user_points(user["id"])
    return {"points": pts}


@router.get("/odds/{match_id}")
async def read_odds(match_id: str):
    m = await db.matches.find_one({"id": match_id}, {"_id": 0, "odds": 1, "bet_locks": 1, "status": 1,
                                                       "home_score": 1, "away_score": 1})
    if not m:
        raise HTTPException(404, "Maç bulunamadı")
    return {
        "match_id": match_id,
        "odds": m.get("odds") or None,
        "bet_locks": m.get("bet_locks") or {},
        "status": m.get("status") or "scheduled",
        "bettable": m.get("status") == "scheduled" and bool(m.get("odds")),
    }


@router.post("/odds/generate/{match_id}")
async def admin_generate_odds(match_id: str, admin: dict = Depends(require_founder)):
    odds = await generate_and_save_odds(match_id)
    return {"match_id": match_id, "odds": odds}


@router.post("/odds/override")
async def admin_override_odds(req: OddsOverrideReq, admin: dict = Depends(require_founder)):
    m = await db.matches.find_one({"id": req.match_id})
    if not m:
        raise HTTPException(404, "Maç bulunamadı")
    current = m.get("odds") or dict(DEFAULT_ODDS)
    for k in ALL_ODDS_KEYS:
        v = req.odds.get(k)
        if v is not None:
            try:
                fv = float(v)
                if 1.05 <= fv <= 100.0:
                    current[k] = round(fv, 2)
            except (TypeError, ValueError):
                pass
    await db.matches.update_one({"id": req.match_id}, {"$set": {"odds": current, "odds_overridden_at": now_iso()}})
    return {"odds": current}


@router.post("/bet-lock")
async def admin_bet_lock(req: BetLockReq, admin: dict = Depends(require_founder)):
    if req.bet_type not in BET_TYPES:
        raise HTTPException(400, "Geçersiz bahis türü")
    field = f"bet_locks.{req.bet_type}"
    await db.matches.update_one({"id": req.match_id}, {"$set": {field: bool(req.locked)}})
    m = await db.matches.find_one({"id": req.match_id}, {"_id": 0, "bet_locks": 1})
    return {"bet_locks": (m or {}).get("bet_locks", {})}


@router.post("/coupons")
async def create_coupon(req: CouponCreateReq, user: dict = Depends(get_current_user)):
    if req.stake < MIN_STAKE:
        raise HTTPException(400, f"Minimum bahis {MIN_STAKE} coin")
    if not req.items:
        raise HTTPException(400, "En az bir seçim ekleyin")

    seen_matches = set()
    validated = []
    total_odd = 1.0
    for it in req.items:
        if it.match_id in seen_matches:
            raise HTTPException(400, "Bir maça yalnızca bir bahis eklenebilir")
        seen_matches.add(it.match_id)
        if it.bet_type not in BET_TYPES:
            raise HTTPException(400, f"Geçersiz bahis türü: {it.bet_type}")
        if it.selection not in SELECTIONS[it.bet_type]:
            raise HTTPException(400, f"Geçersiz seçim: {it.selection}")

        m = await db.matches.find_one({"id": it.match_id}, {"_id": 0})
        if not m:
            raise HTTPException(404, f"Maç bulunamadı: {it.match_id}")
        if m.get("status") != "scheduled":
            raise HTTPException(400, "Sadece programlanmış maçlara bahis oynanabilir")
        locks = m.get("bet_locks") or {}
        if locks.get(it.bet_type):
            raise HTTPException(400, f"Bu maçta {it.bet_type} bahsi kapatıldı")
        odds = m.get("odds") or {}
        odds_key = ODDS_KEYS[it.bet_type][it.selection]
        if odds_key not in odds:
            raise HTTPException(400, "Bu maç için oranlar henüz oluşturulmadı")
        odd = float(odds[odds_key])
        total_odd *= odd
        validated.append({
            "match_id": it.match_id,
            "bet_type": it.bet_type,
            "selection": it.selection,
            "odd": round(odd, 2),
            "status": "PENDING",
        })

    total_odd = round(total_odd, 2)
    potential = round(req.stake * total_odd)

    # Deduct points atomically
    pts = await ensure_user_points(user["id"])
    if pts < req.stake:
        raise HTTPException(400, "Yetersiz bakiye")
    upd = await db.users.update_one(
        {"id": user["id"], "points": {"$gte": req.stake}},
        {"$inc": {"points": -req.stake}}
    )
    if upd.modified_count != 1:
        raise HTTPException(400, "Bakiye yetersiz veya işlem başarısız")

    doc = {
        "id": new_id(),
        "user_id": user["id"],
        "username": user["username"],
        "items": validated,
        "stake": req.stake,
        "total_odd": total_odd,
        "potential_payout": potential,
        "status": "PENDING",
        "created_at": now_iso(),
    }
    await db.coupons.insert_one(dict(doc))
    return doc


async def _enrich_coupon(c: dict) -> dict:
    items = []
    for it in c.get("items", []):
        m = await db.matches.find_one({"id": it["match_id"]}, {"_id": 0, "home_team_id": 1, "away_team_id": 1,
                                                                 "home_score": 1, "away_score": 1,
                                                                 "home_corners": 1, "away_corners": 1,
                                                                 "status": 1, "scheduled_time": 1})
        home = None
        away = None
        if m:
            hteam = await db.teams.find_one({"id": m["home_team_id"]}, {"_id": 0, "id": 1, "name": 1, "abbreviation": 1, "logo_url": 1})
            ateam = await db.teams.find_one({"id": m["away_team_id"]}, {"_id": 0, "id": 1, "name": 1, "abbreviation": 1, "logo_url": 1})
            home = hteam
            away = ateam
        items.append({
            **it,
            "match": {
                **(m or {}),
                "home": home,
                "away": away,
            } if m else None,
        })
    return {**c, "items": items}


@router.get("/coupons/mine")
async def my_coupons(user: dict = Depends(get_current_user)):
    coupons = await db.coupons.find({"user_id": user["id"]}, {"_id": 0}).sort([("created_at", -1)]).to_list(200)
    return [await _enrich_coupon(c) for c in coupons]


# ----------------------------- Public H2H -----------------------------
@router.get("/h2h/{team_a_id}/{team_b_id}")
async def h2h_public(team_a_id: str, team_b_id: str):
    a = await db.teams.find_one({"id": team_a_id}, {"_id": 0, "id": 1, "name": 1, "abbreviation": 1, "logo_url": 1})
    b = await db.teams.find_one({"id": team_b_id}, {"_id": 0, "id": 1, "name": 1, "abbreviation": 1, "logo_url": 1})
    if not a or not b:
        raise HTTPException(404, "Takım bulunamadı")
    stats = await _h2h_stats(team_a_id, team_b_id)
    # Recent matches (last 10)
    matches = await db.matches.find(
        {"status": "finished",
         "$or": [
             {"home_team_id": team_a_id, "away_team_id": team_b_id},
             {"home_team_id": team_b_id, "away_team_id": team_a_id},
         ],
         "home_score": {"$ne": None}},
        {"_id": 0}
    ).sort([("finished_at", -1)]).limit(10).to_list(10)
    recent = []
    for m in matches:
        recent.append({
            "id": m.get("id"),
            "home_team_id": m["home_team_id"],
            "away_team_id": m["away_team_id"],
            "home_score": m.get("home_score"),
            "away_score": m.get("away_score"),
            "home_corners": m.get("home_corners"),
            "away_corners": m.get("away_corners"),
            "finished_at": m.get("finished_at"),
            "week": m.get("week"),
        })
    return {"team_a": a, "team_b": b, "stats": stats, "recent": recent}


# ----------------------------- Founder / Admin Panel -----------------------------
@router.get("/founder/coupons")
async def founder_coupons(admin: dict = Depends(require_founder),
                          status: Optional[str] = None,
                          user_id: Optional[str] = None,
                          limit: int = 500):
    q = {}
    if status:
        q["status"] = status
    if user_id:
        q["user_id"] = user_id
    coupons = await db.coupons.find(q, {"_id": 0}).sort([("created_at", -1)]).limit(limit).to_list(limit)
    return [await _enrich_coupon(c) for c in coupons]


@router.get("/founder/users")
async def founder_users(admin: dict = Depends(require_founder)):
    users = await db.users.find({}, {"_id": 0, "id": 1, "username": 1, "role": 1, "points": 1, "team_id": 1}).to_list(5000)
    for u in users:
        if "points" not in u:
            u["points"] = DEFAULT_STARTING_POINTS
    # Aggregate coupon stats
    agg = await db.coupons.aggregate([
        {"$group": {"_id": "$user_id",
                    "total": {"$sum": 1},
                    "won": {"$sum": {"$cond": [{"$eq": ["$status", "WON"]}, 1, 0]}},
                    "lost": {"$sum": {"$cond": [{"$eq": ["$status", "LOST"]}, 1, 0]}},
                    "pending": {"$sum": {"$cond": [{"$eq": ["$status", "PENDING"]}, 1, 0]}},
                    "staked": {"$sum": "$stake"},
                    "won_amount": {"$sum": {"$cond": [{"$eq": ["$status", "WON"]}, "$payout", 0]}}}}
    ]).to_list(5000)
    agg_map = {a["_id"]: a for a in agg}
    for u in users:
        st = agg_map.get(u["id"], {})
        u["stats"] = {
            "total_coupons": st.get("total", 0),
            "won": st.get("won", 0),
            "lost": st.get("lost", 0),
            "pending": st.get("pending", 0),
            "total_staked": st.get("staked", 0),
            "total_won": st.get("won_amount", 0),
        }
    return users


@router.post("/founder/users/{user_id}/points")
async def founder_set_points(user_id: str, req: UserPointsReq, admin: dict = Depends(require_founder)):
    u = await db.users.find_one({"id": user_id})
    if not u:
        raise HTTPException(404, "Kullanıcı bulunamadı")
    if req.set_to is not None:
        await db.users.update_one({"id": user_id}, {"$set": {"points": int(req.set_to)}})
    elif req.delta is not None:
        await db.users.update_one({"id": user_id}, {"$inc": {"points": int(req.delta)}})
    else:
        raise HTTPException(400, "delta veya set_to gerekli")
    u2 = await db.users.find_one({"id": user_id}, {"_id": 0, "id": 1, "username": 1, "points": 1})
    return u2


@router.post("/founder/coupons/{coupon_id}/cancel")
async def founder_cancel_coupon(coupon_id: str, admin: dict = Depends(require_founder)):
    c = await db.coupons.find_one({"id": coupon_id}, {"_id": 0})
    if not c:
        raise HTTPException(404, "Kupon bulunamadı")
    if c.get("status") == "REFUNDED":
        raise HTTPException(400, "Kupon zaten iade edildi")
    # Refund stake
    await db.users.update_one({"id": c["user_id"]}, {"$inc": {"points": int(c["stake"])}})
    # If it was WON, deduct the payout
    if c.get("status") == "WON" and c.get("payout"):
        await db.users.update_one({"id": c["user_id"]}, {"$inc": {"points": -int(c["payout"])}})
    await db.coupons.update_one({"id": coupon_id}, {"$set": {"status": "REFUNDED",
                                                              "canceled_at": now_iso(),
                                                              "canceled_by": admin["username"]}})
    try:
        await broadcast_push("↩️ Kuponun iade edildi",
                             f"{c['stake']} coin bakiyene geri yatırıldı.",
                             "/my-coupons")
    except Exception:
        pass
    return {"status": "REFUNDED"}


@router.post("/founder/coupons/{coupon_id}/set-status")
async def founder_set_coupon_status(coupon_id: str, req: CouponStatusReq, admin: dict = Depends(require_founder)):
    if req.status not in ("WON", "LOST", "PENDING"):
        raise HTTPException(400, "Geçersiz durum")
    c = await db.coupons.find_one({"id": coupon_id}, {"_id": 0})
    if not c:
        raise HTTPException(404, "Kupon bulunamadı")
    prev = c.get("status")
    payout = int(c.get("payout") or 0)
    # Reverse previous payout if any
    if prev == "WON" and payout:
        await db.users.update_one({"id": c["user_id"]}, {"$inc": {"points": -payout}})

    update = {"status": req.status, "settled_at": now_iso(), "manual_override_by": admin["username"]}
    if req.status == "WON":
        new_payout = round(c["stake"] * c["total_odd"])
        update["payout"] = new_payout
        await db.users.update_one({"id": c["user_id"]}, {"$inc": {"points": new_payout}})
    else:
        update["payout"] = 0

    await db.coupons.update_one({"id": coupon_id}, {"$set": update})
    try:
        if req.status == "WON":
            await broadcast_push("🎉 Kupon Kazandı!", f"+{update['payout']} coin", "/my-coupons")
        elif req.status == "LOST":
            await broadcast_push("💔 Kupon Kaybetti", "Kurucu manuel olarak güncelledi.", "/my-coupons")
    except Exception:
        pass
    return {"status": req.status, "payout": update.get("payout", 0)}


@router.get("/founder/stats")
async def founder_stats(admin: dict = Depends(require_founder)):
    now = datetime.now(timezone.utc)
    day_start = now.replace(hour=0, minute=0, second=0, microsecond=0).isoformat()
    today = await db.coupons.aggregate([
        {"$match": {"created_at": {"$gte": day_start}}},
        {"$group": {"_id": None,
                    "count": {"$sum": 1},
                    "staked": {"$sum": "$stake"},
                    "won_amount": {"$sum": {"$cond": [{"$eq": ["$status", "WON"]}, "$payout", 0]}}}}
    ]).to_list(1)
    all_time = await db.coupons.aggregate([
        {"$group": {"_id": None,
                    "count": {"$sum": 1},
                    "staked": {"$sum": "$stake"},
                    "won_amount": {"$sum": {"$cond": [{"$eq": ["$status", "WON"]}, "$payout", 0]}},
                    "pending": {"$sum": {"$cond": [{"$eq": ["$status", "PENDING"]}, 1, 0]}}}}
    ]).to_list(1)
    t = today[0] if today else {"count": 0, "staked": 0, "won_amount": 0}
    a = all_time[0] if all_time else {"count": 0, "staked": 0, "won_amount": 0, "pending": 0}
    # Money supply
    users = await db.users.find({}, {"_id": 0, "points": 1}).to_list(5000)
    total_points = sum(int(u.get("points") or 0) for u in users)
    return {
        "today": {"count": t.get("count", 0), "staked": t.get("staked", 0), "won": t.get("won_amount", 0)},
        "all_time": {"count": a.get("count", 0), "staked": a.get("staked", 0),
                     "won": a.get("won_amount", 0), "pending": a.get("pending", 0)},
        "total_points_in_circulation": total_points,
    }


# ----------------------------- Migration helper -----------------------------
async def ensure_all_users_have_points():
    await db.users.update_many({"points": {"$exists": False}}, {"$set": {"points": DEFAULT_STARTING_POINTS}})
