// Formation slot layouts. Pitch is vertical; attackers near top (low y%), GK at bottom.
// Coordinates are percentages relative to the pitch container.
export const FORMATIONS = {
  "4-3-3": [
    { key: "GK", label: "KL", x: 50, y: 90 },
    { key: "LB", label: "SLB", x: 16, y: 72 },
    { key: "CB1", label: "STP", x: 38, y: 76 },
    { key: "CB2", label: "STP", x: 62, y: 76 },
    { key: "RB", label: "SĞB", x: 84, y: 72 },
    { key: "CM1", label: "OS", x: 28, y: 50 },
    { key: "CM2", label: "OS", x: 50, y: 53 },
    { key: "CM3", label: "OS", x: 72, y: 50 },
    { key: "LW", label: "SLK", x: 20, y: 24 },
    { key: "ST", label: "SF", x: 50, y: 18 },
    { key: "RW", label: "SĞK", x: 80, y: 24 },
  ],
  "4-4-2": [
    { key: "GK", label: "KL", x: 50, y: 90 },
    { key: "LB", label: "SLB", x: 16, y: 72 },
    { key: "CB1", label: "STP", x: 38, y: 76 },
    { key: "CB2", label: "STP", x: 62, y: 76 },
    { key: "RB", label: "SĞB", x: 84, y: 72 },
    { key: "LM", label: "SLO", x: 16, y: 48 },
    { key: "CM1", label: "OS", x: 40, y: 52 },
    { key: "CM2", label: "OS", x: 60, y: 52 },
    { key: "RM", label: "SĞO", x: 84, y: 48 },
    { key: "ST1", label: "SF", x: 38, y: 20 },
    { key: "ST2", label: "SF", x: 62, y: 20 },
  ],
  "3-5-2": [
    { key: "GK", label: "KL", x: 50, y: 90 },
    { key: "CB1", label: "STP", x: 28, y: 76 },
    { key: "CB2", label: "STP", x: 50, y: 78 },
    { key: "CB3", label: "STP", x: 72, y: 76 },
    { key: "LWB", label: "SLK", x: 12, y: 52 },
    { key: "CM1", label: "OS", x: 35, y: 54 },
    { key: "CM2", label: "OS", x: 50, y: 50 },
    { key: "CM3", label: "OS", x: 65, y: 54 },
    { key: "RWB", label: "SĞK", x: 88, y: 52 },
    { key: "ST1", label: "SF", x: 38, y: 20 },
    { key: "ST2", label: "SF", x: 62, y: 20 },
  ],
  "4-2-3-1": [
    { key: "GK", label: "KL", x: 50, y: 90 },
    { key: "LB", label: "SLB", x: 16, y: 73 },
    { key: "CB1", label: "STP", x: 38, y: 77 },
    { key: "CB2", label: "STP", x: 62, y: 77 },
    { key: "RB", label: "SĞB", x: 84, y: 73 },
    { key: "DM1", label: "DOS", x: 38, y: 58 },
    { key: "DM2", label: "DOS", x: 62, y: 58 },
    { key: "AML", label: "SLK", x: 20, y: 36 },
    { key: "AMC", label: "OOS", x: 50, y: 38 },
    { key: "AMR", label: "SĞK", x: 80, y: 36 },
    { key: "ST", label: "SF", x: 50, y: 16 },
  ],
  "3-4-3": [
    { key: "GK", label: "KL", x: 50, y: 90 },
    { key: "CB1", label: "STP", x: 28, y: 76 },
    { key: "CB2", label: "STP", x: 50, y: 78 },
    { key: "CB3", label: "STP", x: 72, y: 76 },
    { key: "LM", label: "SLO", x: 16, y: 50 },
    { key: "CM1", label: "OS", x: 40, y: 53 },
    { key: "CM2", label: "OS", x: 60, y: 53 },
    { key: "RM", label: "SĞO", x: 84, y: 50 },
    { key: "LW", label: "SLK", x: 22, y: 24 },
    { key: "ST", label: "SF", x: 50, y: 18 },
    { key: "RW", label: "SĞK", x: 78, y: 24 },
  ],
  "5-3-2": [
    { key: "GK", label: "KL", x: 50, y: 90 },
    { key: "LWB", label: "SLB", x: 10, y: 64 },
    { key: "CB1", label: "STP", x: 30, y: 77 },
    { key: "CB2", label: "STP", x: 50, y: 79 },
    { key: "CB3", label: "STP", x: 70, y: 77 },
    { key: "RWB", label: "SĞB", x: 90, y: 64 },
    { key: "CM1", label: "OS", x: 32, y: 48 },
    { key: "CM2", label: "OS", x: 50, y: 50 },
    { key: "CM3", label: "OS", x: 68, y: 48 },
    { key: "ST1", label: "SF", x: 38, y: 20 },
    { key: "ST2", label: "SF", x: 62, y: 20 },
  ],
  "4-1-4-1": [
    { key: "GK", label: "KL", x: 50, y: 90 },
    { key: "LB", label: "SLB", x: 16, y: 73 },
    { key: "CB1", label: "STP", x: 38, y: 77 },
    { key: "CB2", label: "STP", x: 62, y: 77 },
    { key: "RB", label: "SĞB", x: 84, y: 73 },
    { key: "DM", label: "DOS", x: 50, y: 58 },
    { key: "LM", label: "SLK", x: 18, y: 40 },
    { key: "CM1", label: "OS", x: 40, y: 42 },
    { key: "CM2", label: "OS", x: 60, y: 42 },
    { key: "RM", label: "SĞK", x: 82, y: 40 },
    { key: "ST", label: "SF", x: 50, y: 18 },
  ],
};

export const FORMATION_NAMES = Object.keys(FORMATIONS);
